### ISSUE TITLE
Rename package to include beta-cell function indices?

### ISSUE THREAD

**Issue by lwjohnst86** [jcpsantiago/IScalc#2]
Related to #1, since the package could also calculating BCF, maybe rename to something more inclusive. Like `ogtt` or maybe like `edpi` (estimated diabetes pathophysiological indices... yea, I know its wordy).

**Comment by jcpsantiago** [comment]
what about just `diabetes-indices`, more google friendly and opens the door to include the beta-cell functions and maybe even clamp-based too

**Comment by lwjohnst86** [comment]
True. Though R packages can't have `-`, so `diabetes.indices`? Might be nice if it was shorter though. What about `dm.indices`?

**Comment by jcpsantiago** [comment]
renamed to `gmi` as in glucose metabolic indices, so it's more general and easier to call functions with e.g. `gmi::matsuda()` thanks @lwjohnst86
